version: '3.1'

services:
    php:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '5656:80'
        volumes:
            - ./app:/var/www/html

    db:
        image: 'mariadb'
        restart: always
        environment:
            MYSQL_DATABASE: data
            MYSQL_ROOT_PASSWORD: password
        volumes:
            - ./database/dump.sql:/docker-entrypoint-initdb.d/dump.sql


    adminer:
        image: adminer
        restart: always
        ports:
            - '5050:8080'
        environment:
            - PMA_ARBITRARY=1
